import type { PenType } from './types'

export type RenderStyle = 'smooth' | 'textured' | 'calligraphy' | 'watercolor' | 'marker' | 'pattern'
export type PatternKind = 'crosshatch' | 'stipple' | 'grid' | 'brick' | 'halftone'
export type PenCategory = 'boceto' | 'tinta' | 'pintura' | 'pastel' | 'textura' | 'destacado'

export interface PenPreset {
  id: PenType
  label: string
  description: string
  icon: string
  category: PenCategory
  minWidth: number
  maxWidth: number
  defaultWidth: number
  opacity: number
  pressureSensitive: boolean
  render: RenderStyle
  pattern?: PatternKind
  supportsStraightLine: boolean
}

export const PEN_CATEGORIES: { id: PenCategory; label: string }[] = [
  { id: 'boceto', label: 'Boceto' },
  { id: 'tinta', label: 'Tinta' },
  { id: 'pintura', label: 'Pintura' },
  { id: 'pastel', label: 'Pastel' },
  { id: 'textura', label: 'Textura' },
  { id: 'destacado', label: 'Destacado' },
]

export const PEN_PRESETS: PenPreset[] = [
  {
    id: 'pencil',
    label: 'Lápiz HB',
    description: 'Grafito clásico con grano suave, sensible a la presión.',
    icon: '✏️',
    category: 'boceto',
    minWidth: 1,
    maxWidth: 6,
    defaultWidth: 2,
    opacity: 0.85,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'mechanicalPencil',
    label: 'Portaminas',
    description: 'Línea fina y constante, sin variación de grano.',
    icon: '✏️',
    category: 'boceto',
    minWidth: 0.5,
    maxWidth: 3,
    defaultWidth: 1,
    opacity: 0.95,
    pressureSensitive: false,
    render: 'smooth',
    supportsStraightLine: false,
  },
  {
    id: 'coloredPencil',
    label: 'Lápiz de color',
    description: 'Grano seco y ligero, ideal para dar color a bocetos.',
    icon: '🖍️',
    category: 'boceto',
    minWidth: 1,
    maxWidth: 8,
    defaultWidth: 3,
    opacity: 0.7,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'pencil2H',
    label: 'Grafito 2H',
    description: 'Mina dura: línea clara y precisa, ideal para boceto ligero.',
    icon: '✏️',
    category: 'boceto',
    minWidth: 0.5,
    maxWidth: 4,
    defaultWidth: 1.5,
    opacity: 0.55,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'pencil6B',
    label: 'Grafito 6B',
    description: 'Mina blanda: trazo oscuro y graso, ideal para sombreado denso.',
    icon: '✏️',
    category: 'boceto',
    minWidth: 1.5,
    maxWidth: 10,
    defaultWidth: 4,
    opacity: 0.95,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'charcoal',
    label: 'Carboncillo',
    description: 'Grano grueso e irregular, ideal para sombreado suelto.',
    icon: '🪨',
    category: 'boceto',
    minWidth: 3,
    maxWidth: 18,
    defaultWidth: 8,
    opacity: 0.9,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'fineliner',
    label: 'Bolígrafo fino',
    description: 'Línea uniforme y precisa, sin variación de presión.',
    icon: '🖊️',
    category: 'tinta',
    minWidth: 1,
    maxWidth: 4,
    defaultWidth: 2,
    opacity: 1,
    pressureSensitive: false,
    render: 'smooth',
    supportsStraightLine: false,
  },
  {
    id: 'ballpoint',
    label: 'Bolígrafo',
    description: 'Trazo fino y consistente, con leve variación de presión.',
    icon: '🖊️',
    category: 'tinta',
    minWidth: 1,
    maxWidth: 3.5,
    defaultWidth: 1.6,
    opacity: 1,
    pressureSensitive: true,
    render: 'smooth',
    supportsStraightLine: false,
  },
  {
    id: 'gelPen',
    label: 'Bolígrafo de gel',
    description: 'Tinta densa y brillante, trazo suave y uniforme.',
    icon: '🖊️',
    category: 'tinta',
    minWidth: 1.5,
    maxWidth: 6,
    defaultWidth: 2.5,
    opacity: 1,
    pressureSensitive: true,
    render: 'smooth',
    supportsStraightLine: false,
  },
  {
    id: 'fountain',
    label: 'Pluma',
    description: 'Tinta fluida con trazo que responde a la presión.',
    icon: '🖋️',
    category: 'tinta',
    minWidth: 1,
    maxWidth: 10,
    defaultWidth: 3,
    opacity: 1,
    pressureSensitive: true,
    render: 'smooth',
    supportsStraightLine: false,
  },
  {
    id: 'calligraphy',
    label: 'Caligrafía',
    description: 'Plumín en ángulo: fino en vertical, grueso en diagonal.',
    icon: '✒️',
    category: 'tinta',
    minWidth: 3,
    maxWidth: 16,
    defaultWidth: 8,
    opacity: 1,
    pressureSensitive: true,
    render: 'calligraphy',
    supportsStraightLine: false,
  },
  {
    id: 'inkBrush',
    label: 'Pincel de tinta',
    description: 'Pincel oriental: trazo muy expresivo entre grosor y presión.',
    icon: '🖌️',
    category: 'tinta',
    minWidth: 1,
    maxWidth: 20,
    defaultWidth: 6,
    opacity: 1,
    pressureSensitive: true,
    render: 'calligraphy',
    supportsStraightLine: false,
  },
  {
    id: 'brush',
    label: 'Pincel artístico',
    description: 'Cerdas suaves con carga de presión, ideal para ilustración.',
    icon: '🖌️',
    category: 'pintura',
    minWidth: 2,
    maxWidth: 24,
    defaultWidth: 10,
    opacity: 0.9,
    pressureSensitive: true,
    render: 'smooth',
    supportsStraightLine: false,
  },
  {
    id: 'watercolor',
    label: 'Acuarela',
    description: 'Capas translúcidas superpuestas, efecto de tinta aguada.',
    icon: '🎨',
    category: 'pintura',
    minWidth: 8,
    maxWidth: 40,
    defaultWidth: 20,
    opacity: 0.5,
    pressureSensitive: true,
    render: 'watercolor',
    supportsStraightLine: false,
  },
  {
    id: 'pastel',
    label: 'Pastel',
    description: 'Pigmento suave y polvoriento, mezcla bien las capas.',
    icon: '🎨',
    category: 'pastel',
    minWidth: 6,
    maxWidth: 30,
    defaultWidth: 14,
    opacity: 0.6,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'softPastel',
    label: 'Pastel suave',
    description: 'Pigmento muy fino y aterciopelado, se difumina con facilidad.',
    icon: '🖍️',
    category: 'pastel',
    minWidth: 8,
    maxWidth: 34,
    defaultWidth: 18,
    opacity: 0.45,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'oilPastel',
    label: 'Pastel al óleo',
    description: 'Pigmento graso y denso, cubre con un trazo cargado.',
    icon: '🖍️',
    category: 'pastel',
    minWidth: 6,
    maxWidth: 28,
    defaultWidth: 16,
    opacity: 0.85,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'marker',
    label: 'Rotulador',
    description: 'Trazo plano semi-opaco con puntas cuadradas.',
    icon: '🖊️',
    category: 'pintura',
    minWidth: 6,
    maxWidth: 20,
    defaultWidth: 12,
    opacity: 0.65,
    pressureSensitive: false,
    render: 'marker',
    supportsStraightLine: true,
  },
  {
    id: 'chalk',
    label: 'Tiza',
    description: 'Grano áspero y mate, típico de pizarra.',
    icon: '🪨',
    category: 'textura',
    minWidth: 4,
    maxWidth: 24,
    defaultWidth: 12,
    opacity: 0.75,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'crayon',
    label: 'Cera',
    description: 'Trazo graso e irregular, con textura de crayón.',
    icon: '🖍️',
    category: 'textura',
    minWidth: 4,
    maxWidth: 26,
    defaultWidth: 14,
    opacity: 0.8,
    pressureSensitive: true,
    render: 'textured',
    supportsStraightLine: false,
  },
  {
    id: 'glitter',
    label: 'Purpurina',
    description: 'Partículas brillantes dispersas a lo largo del trazo.',
    icon: '✨',
    category: 'textura',
    minWidth: 8,
    maxWidth: 30,
    defaultWidth: 16,
    opacity: 0.9,
    pressureSensitive: false,
    render: 'pattern',
    pattern: 'stipple',
    supportsStraightLine: false,
  },
  {
    id: 'crosshatch',
    label: 'Rayado cruzado',
    description: 'Estampa líneas cruzadas a lo largo del trazo, para sombreado.',
    icon: '⛌',
    category: 'textura',
    minWidth: 10,
    maxWidth: 34,
    defaultWidth: 18,
    opacity: 0.8,
    pressureSensitive: true,
    render: 'pattern',
    pattern: 'crosshatch',
    supportsStraightLine: false,
  },
  {
    id: 'stipple',
    label: 'Punteado',
    description: 'Nube de puntos irregulares, ideal para texturas y grano.',
    icon: '⠿',
    category: 'textura',
    minWidth: 10,
    maxWidth: 40,
    defaultWidth: 20,
    opacity: 0.85,
    pressureSensitive: true,
    render: 'pattern',
    pattern: 'stipple',
    supportsStraightLine: false,
  },
  {
    id: 'gridTexture',
    label: 'Cuadrícula',
    description: 'Estampa una retícula fina a lo largo del trazo.',
    icon: '▦',
    category: 'textura',
    minWidth: 12,
    maxWidth: 36,
    defaultWidth: 20,
    opacity: 0.8,
    pressureSensitive: false,
    render: 'pattern',
    pattern: 'grid',
    supportsStraightLine: false,
  },
  {
    id: 'halftoneDots',
    label: 'Medio tono',
    description: 'Trama regular de puntos, como una impresión de medio tono.',
    icon: '⣿',
    category: 'textura',
    minWidth: 10,
    maxWidth: 36,
    defaultWidth: 18,
    opacity: 0.85,
    pressureSensitive: true,
    render: 'pattern',
    pattern: 'halftone',
    supportsStraightLine: false,
  },
  {
    id: 'brick',
    label: 'Mosaico',
    description: 'Bloques rectangulares alternados tipo ladrillo.',
    icon: '🧱',
    category: 'textura',
    minWidth: 12,
    maxWidth: 36,
    defaultWidth: 20,
    opacity: 0.85,
    pressureSensitive: false,
    render: 'pattern',
    pattern: 'brick',
    supportsStraightLine: false,
  },
  {
    id: 'highlighter',
    label: 'Subrayador',
    description: 'Muy transparente, con modo de línea recta para subrayar.',
    icon: '🖍️',
    category: 'destacado',
    minWidth: 5,
    maxWidth: 30,
    defaultWidth: 16,
    opacity: 0.35,
    pressureSensitive: false,
    render: 'smooth',
    supportsStraightLine: true,
  },
  {
    id: 'neonHighlighter',
    label: 'Subrayador neón',
    description: 'Color vivo y saturado, ideal para resaltar con fuerza.',
    icon: '🖍️',
    category: 'destacado',
    minWidth: 5,
    maxWidth: 34,
    defaultWidth: 18,
    opacity: 0.55,
    pressureSensitive: false,
    render: 'marker',
    supportsStraightLine: true,
  },
]

export function getPenPreset(id: PenType): PenPreset {
  return PEN_PRESETS.find((p) => p.id === id) ?? PEN_PRESETS[0]
}
